name: Tests for lab and deployment

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TESTS: 1

jobs:
  push-student:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
      - uses: actions/checkout@v2
      - name: Generate output files for student archive
        run: |
          utils/generate_student_archive
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'congestion-lab-student'
          destination-github-username: 'Aperence'
          destination-repository-name: 'linfo1341-congestion-student'
          user-email: aperence.github.bot@gmail.com
          target-branch: main
      - name: Clean generated files
        run: |
          rm -rf ./congestion-lab-student
